"""depgraph.py — shared machinery for `make check-deps` / `make check-deps-rebuild`.

Stdlib only. Everything here works on a SCRATCH COPY of the working tree, never
on the real build/ directory: the Makefile's parse-time configuration guard
deletes object trees when the signature differs, and these checks deliberately
rebuild, edit headers and rewrite mtimes.

Ground truth for "what does this object include" is ca65 itself. Every build
runs with tool wrappers first on PATH (so a recipe that hard-codes `ca65`
instead of `$(CA65)`, or silences itself with `@`, is still seen). The ca65
wrapper runs the real assembler with the recipe's own arguments untouched,
then a SECOND time with the same arguments, the output redirected to a
scratch file and `--create-full-dep` added. The dependency list therefore
reflects exactly the command line make ran for that object, in that object
tree's configuration (test hooks, archive, Keccak-only manifest), following
every nested `.include` / `.incbin` the assembler actually opened. Nothing is
inferred from the Makefile text or from grepping `.include` lines.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Everything the checks build: the test PRG, both shipped archives, and both
# probe links (which pull every archive member, so their images cover every
# member's bytes).
TARGETS = ["all", "lib", "lib-keccak", "build/mlkem-lib.prg", "build/mlkem-keccak-lib.prg"]
# Linked images and the files shipped next to the archives (compared byte for
# byte: a shipped sqtab_base.inc that is not re-copied is a stale artifact).
IMAGES = ["build/mlkem.prg", "build/labels.txt", "build/mlkem.map",
          "build/mlkem-lib.prg", "build/mlkem-lib.map",
          "build/mlkem-keccak-lib.prg", "build/mlkem-keccak-lib.map"]
# Verbatim copies of sources; not evidence that an edit changed what the
# assembler emitted, so check_deps_rebuild's vacuity test ignores them.
SHIPPED = ["build/lib/mlkem.inc", "build/lib/zp_config.s", "build/lib/sqtab_base.inc",
           "build/lib/cfg/mlkem-example.cfg"]
IMAGES = IMAGES + SHIPPED
ARCHIVES = ["build/lib/mlkem.a", "build/lib/mlkem-keccak.a"]

# Fixed mtimes, all in the past. GNU Make 3.81 (macOS) compares mtimes at
# 1-second granularity, so "edit the header, then make" can see the header and
# the object it should invalidate in the SAME second and rebuild nothing — a
# false green that depends on the wall clock. These checks never sleep and
# never rely on "now": every source file is set to T_SRC, every build output
# to T_BUILD (one hour later), and a probed/edited header to T_EDIT (one hour
# later again), with os.utime / `touch -t`. The ordering is then strict by
# 3600 s regardless of how fast the machine is, and nothing is in the future,
# so make never prints clock-skew warnings.
T_SRC = "202001010000"      # touch -t format, local time
T_BUILD = "202001010100"
T_EDIT = "202001010200"
# Second tier, for scenarios that build once more before the edit.
T_BUILD2 = "202001010300"
T_EDIT2 = "202001010400"

SCRUB_ENV = ["MAKEFLAGS", "MFLAGS", "MAKELEVEL", "MAKEFILES", "MAKEOVERRIDES",
             "CA65FLAGS", "CONTRACT_DEFINES", "CONTRACT_ZP_DEFINES", "GNUMAKEFLAGS"]

WRAPPER = r'''#!%(python)s
# generated by tools/depgraph.py — logs the invocation, runs the real tool,
# and (ca65 only) records the object's full dependency list.
import json, os, subprocess, sys, tempfile
REAL = %(real)r
TOOL = %(tool)r
args = sys.argv[1:]
rc = subprocess.call([REAL] + args)
log = os.environ.get("DEPCHK_LOG")
rec = {"tool": TOOL, "argv": args, "cwd": os.getcwd(), "rc": rc}
if TOOL == "ca65" and rc == 0 and os.environ.get("DEPCHK_GRAPH"):
    out, src, clean, i = None, None, [], 0
    while i < len(args):
        a = args[i]
        if a in ("-o", "--create-dep", "--create-full-dep", "-l", "--listing"):
            if a == "-o":
                out = args[i + 1]
            i += 2
            continue
        if not a.startswith("-") and (i == 0 or args[i - 1] not in (
                "-D", "-I", "-t", "--target", "--cpu", "--include-dir",
                "--bin-include-dir", "-W", "--feature", "-mm", "--memory-model",
                "--list-bytes", "--pagelength")):
            src = a
        clean.append(a)
        i += 1
    if out is None and src is not None:
        out = os.path.splitext(src)[0] + ".o"
    d = tempfile.mkdtemp(prefix="depchk-")
    try:
        r2 = subprocess.call([REAL] + clean + ["-o", os.path.join(d, "x.o"),
                                               "--create-full-dep", os.path.join(d, "x.d")])
        text = open(os.path.join(d, "x.d")).read() if r2 == 0 else ""
    finally:
        for f in os.listdir(d):
            os.unlink(os.path.join(d, f))
        os.rmdir(d)
    text = text.replace("\\\n", " ")
    first = text.split("\n", 1)[0]
    deps = first.split(":", 1)[1].split() if ":" in first else []
    rec.update({"obj": out, "src": src, "deps": deps, "deprc": r2})
if log:
    with open(log, "a") as f:
        f.write(json.dumps(rec) + "\n")
sys.exit(rc)
'''


def die(msg):
    print(msg)
    sys.exit(2)


def which_real(tool):
    for d in os.environ.get("PATH", "").split(os.pathsep):
        p = os.path.join(d, tool)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return p
    die("FATAL: %s not found on PATH" % tool)


class Scratch:
    """A scratch copy of the working tree plus tool wrappers."""

    def __init__(self, keep=False):
        self.keep = keep
        self.root = os.path.realpath(tempfile.mkdtemp(prefix="c64-mlkem-deps."))
        self.bin = os.path.join(self.root, "bin")
        os.mkdir(self.bin)
        for tool in ("ca65", "ld65", "ar65"):
            real = which_real(tool)
            p = os.path.join(self.bin, tool)
            with open(p, "w") as f:
                f.write(WRAPPER % {"python": sys.executable, "real": real, "tool": tool})
            os.chmod(p, 0o755)
        self.od65 = which_real("od65")
        self.ar65 = which_real("ar65")
        self.n = 0

    def close(self):
        if self.keep:
            print("  (scratch kept at %s)" % self.root)
        else:
            shutil.rmtree(self.root, ignore_errors=True)

    def copy_tree(self, name, src=REPO):
        """Copy the working tree (uncommitted edits included) minus build
        products and VCS/agent state. copy2 keeps mtimes; callers normalise
        them anyway."""
        dst = os.path.join(self.root, name)
        ign = shutil.ignore_patterns(".git", ".claude", ".serena", ".ca65-ls",
                                     "__pycache__", "*.pyc")
        def ignore(d, names):
            out = set(ign(d, names))
            if os.path.abspath(d) == os.path.abspath(src) and src == REPO:
                out.add("build")
            return out
        shutil.copytree(src, dst, ignore=ignore, symlinks=True)
        return dst

    def env(self, log=None, graph=False):
        e = dict(os.environ)
        for k in SCRUB_ENV:
            e.pop(k, None)
        e["PATH"] = self.bin + os.pathsep + e.get("PATH", "")
        e.pop("DEPCHK_LOG", None)
        e.pop("DEPCHK_GRAPH", None)
        if log:
            e["DEPCHK_LOG"] = log
        if graph:
            e["DEPCHK_GRAPH"] = "1"
        return e

    def make(self, tree, args, graph=False, dry=False):
        """Run make; return (rc, output, [wrapper records])."""
        self.n += 1
        log = os.path.join(self.root, "log.%d.jsonl" % self.n)
        cmd = ["make", "--no-print-directory"] + (["-n"] if dry else []) + args
        p = subprocess.run(cmd, cwd=tree, env=self.env(log, graph),
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        recs = []
        if os.path.exists(log):
            with open(log) as f:
                recs = [json.loads(l) for l in f if l.strip()]
        return p.returncode, p.stdout, recs


def graph_from_records(tree, recs):
    """{object path (tree-relative): (primary source, sorted [deps])}."""
    g = {}
    for r in recs:
        if r["tool"] != "ca65" or "obj" not in r:
            continue
        if r.get("deprc", 1) != 0:
            die("FATAL: ca65 --create-full-dep failed for %s" % r["obj"])
        tree = os.path.realpath(tree)
        rel = lambda p: os.path.relpath(os.path.realpath(os.path.join(r["cwd"], p)), tree)
        obj = rel(r["obj"])
        if obj.startswith("..") or not obj.endswith(".o"):
            continue        # e.g. a separate .d-only rule assembling to /dev/null
        g[obj] = (rel(r["src"]) if r["src"] else None, sorted({rel(d) for d in r["deps"]}))
    return g


def set_mtime(path, stamp):
    subprocess.check_call(["touch", "-h", "-t", stamp, path])


def normalise_mtimes(tree):
    """Sources -> T_SRC, everything under build/ -> T_BUILD (see T_* above)."""
    import time
    ts = time.mktime(time.strptime(T_SRC, "%Y%m%d%H%M"))
    tb = time.mktime(time.strptime(T_BUILD, "%Y%m%d%H%M"))
    for d, dirs, files in os.walk(tree):
        in_build = os.path.relpath(d, tree).split(os.sep)[0] == "build"
        t = tb if in_build else ts
        for n in files + dirs:
            p = os.path.join(d, n)
            if not os.path.islink(p):
                os.utime(p, (t, t))


def set_build_mtimes(tree, stamp):
    """Everything under build/ -> stamp (sources untouched)."""
    import time
    t = time.mktime(time.strptime(stamp, "%Y%m%d%H%M"))
    for d, dirs, files in os.walk(os.path.join(tree, "build")):
        for n in files + dirs:
            p = os.path.join(d, n)
            if not os.path.islink(p):
                os.utime(p, (t, t))


def tool_lines_in_dry_run(text, tools=("ca65", "ld65", "ar65")):
    """Lines of a `make -n` transcript that would run one of `tools`."""
    import shlex
    hits = []
    for line in text.splitlines():
        try:
            toks = shlex.split(line, comments=False)
        except ValueError:
            toks = line.split()
        if any(os.path.basename(t) in tools for t in toks):
            hits.append(line.strip())
    return hits


def ca65_objects_in_dry_run(text):
    """Objects a `make -n` transcript would assemble (the -o of every ca65)."""
    import shlex
    objs = set()
    for line in text.splitlines():
        try:
            toks = shlex.split(line, comments=False)
        except ValueError:
            toks = line.split()
        run = False
        for i, t in enumerate(toks):
            if t in (";", "&&", "||", "|"):
                run = False
            elif os.path.basename(t) == "ca65":
                run = True
            elif run and t == "-o" and i + 1 < len(toks):
                objs.add(os.path.normpath(toks[i + 1]))
    return objs


def invocations(recs, tools=("ca65", "ld65", "ar65")):
    return [r for r in recs if r["tool"] in tools]
