#!/usr/bin/env python3
"""gen_tables.py — emit the generated .inc tables from the validated models.

    python3 tools/gen_tables.py         > src/keccak_tables.inc
    python3 tools/gen_tables.py --mlkem > src/mlkem_tables.inc

Keccak: the round constants, the fused rho+pi destination map, and the rho
rotation split are all derived from tools/keccak_ref.py, which
tools/test_keccak_ref.py pins against XKCP's published RC/RhoOffset tables and
240 intermediate states.

ML-KEM: the 128 NTT zetas, the 128 basemul gammas and the reduction constants
come from tools/mlkem_ref.py, which tools/test_mlkem_ref.py pins to FIPS 203
Appendix A, the NIST ACVP vectors and cryptography.hazmat.

Generating rather than hand-typing means a transcription slip is impossible.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def emit_mlkem(o):
    import mlkem_ref as M
    Q = M.Q
    R = 1 << 16                                   # Montgomery radix, if used
    mont = lambda x: (x * R) % Q
    # These identities are what the comments below claim; assert them here so
    # the generated file cannot drift from the model it documents.
    assert all(M.GAMMAS[2 * i] == M.ZETAS[64 + i] and
               M.GAMMAS[2 * i + 1] == Q - M.ZETAS[64 + i] for i in range(64))
    assert (M.N_INV * 128) % Q == 1
    qinv = pow(Q, -1, R)
    assert (Q * qinv) % R == 1

    o("; ============================================================================\n")
    o("; mlkem_tables.inc — GENERATED by tools/gen_tables.py --mlkem. Do not hand-edit.\n")
    o(";\n")
    o("; Regenerate with:  make tables   (python3 tools/gen_tables.py --mlkem)\n")
    o("; Source of truth is tools/mlkem_ref.py, pinned to FIPS 203 Appendix A, the\n")
    o("; NIST ACVP ML-KEM-768 vectors and cryptography.hazmat by tools/test_mlkem_ref.py.\n")
    o("; ============================================================================\n\n")

    o("; --- reduction constants (all derived, none typed) ------------------------\n")
    o(f"MLKEM_Q          = {Q:5d}        ; the modulus\n")
    o(f"MLKEM_Q_LO       = ${Q & 0xFF:02X}\n")
    o(f"MLKEM_Q_HI       = ${Q >> 8:02X}\n")
    o(f"MLKEM_NEG_Q16    = ${(-Q) & 0xFFFF:04X}       ; -q mod 2^16, for a 16-bit add-based reduce\n")
    o(f"MLKEM_N_INV      = {M.N_INV:5d}        ; 128^-1 mod q, the INTT scaling (Alg. 10)\n")
    o(f"MLKEM_BARRETT_26 = {(1 << 26) // Q:5d}        ; floor(2^26 / q), Barrett multiplier for 16-bit inputs\n")
    o(f"MLKEM_QINV_16    = {qinv:5d}        ; q^-1 mod 2^16 (Montgomery, R = 2^16)\n")
    o(f"MLKEM_NEG_QINV16 = {(-qinv) % R:5d}        ; -q^-1 mod 2^16\n")
    o(f"MLKEM_MONT_R     = {mont(1):5d}        ; R mod q\n")
    o(f"MLKEM_MONT_R2    = {mont(mont(1)):5d}        ; R^2 mod q (to-Montgomery multiplier)\n")
    o(f"MLKEM_MONT_N_INV = {mont(M.N_INV):5d}        ; 128^-1 * R mod q\n")
    o("\n")

    o("; --- NTT zetas (FIPS 203 Appendix A, bit-reversed order) -------------------\n")
    o(";\n")
    o("; zetas[i] = 17^BitRev7(i) mod q. This IS the traversal order: NTT layer l\n")
    o("; (len = 128 >> l, 2^l butterfly blocks) consumes zetas[2^l .. 2^(l+1)-1] in\n")
    o("; order, one per block, block b at coefficients [b*2*len, (b+1)*2*len):\n")
    for l in range(7):
        ln = 128 >> l
        o(f";   layer {l}: len {ln:3d}, {1 << l:3d} block(s) of {2 * ln:3d}, zetas[{1 << l:3d}..{(2 << l) - 1:3d}]\n")
    o("; INTT (Alg. 10) walks the layers back, len 2 -> 128, and within each\n")
    o("; layer takes the SAME index range in REVERSE (i counts down from\n")
    o("; 2^(l+1)-1), since zetas[2^(l+1)-1-b] == -zetas[2^l+b]^-1 mod q. Each\n")
    o("; inverse layer therefore doubles the values; the final MLKEM_N_INV\n")
    o("; multiply removes the 2^7. zetas[0] = 1 is never used by either.\n")
    o(";\n")
    o("; Split-plane, to match the polynomial layout: 128 low bytes, then 128\n")
    o("; high bytes (0..12). 256 B total, at the §8.0 precalc-table floor.\n")

    def plane(name, vals, shift, comment):
        o(f"{name}:   ; {comment}\n")
        for row in range(0, 128, 16):
            o("        .byte " + ", ".join(f"${((v >> shift) & 0xFF):02X}" for v in vals[row:row + 16])
              + f"   ; [{row:3d}..{row + 15:3d}]\n")

    plane("mlkem_zetas_lo", M.ZETAS, 0, "zetas[i] & $FF")
    plane("mlkem_zetas_hi", M.ZETAS, 8, "zetas[i] >> 8")

    o("\n; --- basemul gammas (Alg. 11/12) ---------------------------------------------\n")
    o(";\n")
    o("; gamma[i] = 17^(2*BitRev7(i)+1) mod q, for coefficient pair (2i, 2i+1).\n")
    o("; Identity (asserted by the generator): gamma[2i] = zetas[64+i] and\n")
    o("; gamma[2i+1] = q - zetas[64+i], so an implementation may index the zeta\n")
    o("; table's top half and negate the odd pairs instead of storing these.\n")
    plane("mlkem_gammas_lo", M.GAMMAS, 0, "gamma[i] & $FF")
    plane("mlkem_gammas_hi", M.GAMMAS, 8, "gamma[i] >> 8")

    o("\n; --- Montgomery-domain copies (zeta * 2^16 mod q), if a Montgomery multiply\n")
    o("; is chosen; unused otherwise. Same order and split as above.\n")
    mz = [mont(z) for z in M.ZETAS]
    plane("mlkem_zetas_mont_lo", mz, 0, "(zetas[i] * 2^16 mod q) & $FF")
    plane("mlkem_zetas_mont_hi", mz, 8, "(zetas[i] * 2^16 mod q) >> 8")


if "--mlkem" in sys.argv:
    emit_mlkem(sys.stdout.write)
    sys.exit(0)

import keccak_ref as K

# Destination lane for source lane i = x + 5y, exactly as the validated
# model's pi(): B[y + 5*((2x+3y) % 5)] = A[x + 5y].
dst = [0] * 25
for y in range(5):
    for x in range(5):
        dst[x + 5 * y] = y + 5 * ((2 * x + 3 * y) % 5)

o = sys.stdout.write
o("; ============================================================================\n")
o("; keccak_tables.inc — GENERATED by tools/gen_tables.py. Do not hand-edit.\n")
o(";\n")
o("; Regenerate with:  python3 tools/gen_tables.py > src/keccak_tables.inc\n")
o("; Source of truth is tools/keccak_ref.py, pinned to XKCP's published tables\n")
o("; and 240 intermediate states by tools/test_keccak_ref.py.\n")
o("; ============================================================================\n\n")

o("; 24 round constants, 8 bytes each, little-endian lanes (192 B).\n")
o("keccak_rc:\n")
for r, v in enumerate(K.RC):
    b = ", ".join(f"${(v >> (8 * k)) & 0xFF:02X}" for k in range(8))
    o(f"        .byte {b}   ; round {r:2d}\n")

# Rotation decomposition, indexed by source lane.
#
#   ROTL64(v, 8s+b) with b <= 4  ==  byte-rotate s, then rotate LEFT b
#   ROTL64(v, 8s+b) with b >  4  ==  byte-rotate s+1, then rotate RIGHT 8-b
#
# because 8s+b == 8(s+1) - (8-b). Taking whichever direction is shorter caps
# the bit passes at 4 instead of 7 and cuts the per-round total from 88 to 52.
# Verified for all 25 lanes in tools/test_keccak_ref.py.
rot_byte, rot_cnt, rot_dir = [], [], []
for i in range(25):
    s, b = K.RHO[i] >> 3, K.RHO[i] & 7
    if b <= 4:
        rot_byte.append(s); rot_cnt.append(b); rot_dir.append(0)
    else:
        rot_byte.append((s + 1) & 7); rot_cnt.append(8 - b); rot_dir.append(1)

o("\n; Fused rho+pi, indexed by SOURCE lane i = x + 5y.\n")
o("; keccak_pi_dst:  destination BYTE offset (8 * destination lane index)\n")
o("; keccak_rot_byte: whole-byte rotation — free, it is just a byte permute\n")
o(";                  applied while copying the lane into its destination\n")
o("; keccak_rot_cnt:  residual bit passes, 0..4\n")
o("; keccak_rot_dir:  0 = rotate left, 1 = rotate right (the short way round)\n")
for name, vals in (("keccak_pi_dst",   [8 * dst[i] for i in range(25)]),
                   ("keccak_rot_byte", rot_byte),
                   ("keccak_rot_cnt",  rot_cnt),
                   ("keccak_rot_dir",  rot_dir)):
    o(f"{name}:\n")
    for row in range(5):
        o("        .byte " + ", ".join(f"{vals[i]:3d}" for i in range(row * 5, row * 5 + 5)) + "\n")
