#!/usr/bin/env python3
"""gen_tables.py — emit src/keccak_tables.inc from the validated model.

The round constants, the fused rho+pi destination map, and the rho rotation
split are all derived from tools/keccak_ref.py, which tools/test_keccak_ref.py
pins against XKCP's published RC/RhoOffset tables and 240 intermediate states.
Generating rather than hand-typing means a transcription slip is impossible.

Usage:  python3 tools/gen_tables.py > src/keccak_tables.inc
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import keccak_ref as K

# Destination lane for source lane i = x + 5y, exactly as the validated
# model's pi(): B[y + 5*((2x+3y) % 5)] = A[x + 5y].
dst = [0] * 25
for y in range(5):
    for x in range(5):
        dst[x + 5 * y] = y + 5 * ((2 * x + 3 * y) % 5)

o = sys.stdout.write
o("; ============================================================================\n")
o("; keccak_tables.inc — GENERATED by tools/gen_tables.py. Do not hand-edit.\n")
o(";\n")
o("; Regenerate with:  python3 tools/gen_tables.py > src/keccak_tables.inc\n")
o("; Source of truth is tools/keccak_ref.py, pinned to XKCP's published tables\n")
o("; and 240 intermediate states by tools/test_keccak_ref.py.\n")
o("; ============================================================================\n\n")

o("; 24 round constants, 8 bytes each, little-endian lanes (192 B).\n")
o("keccak_rc:\n")
for r, v in enumerate(K.RC):
    b = ", ".join(f"${(v >> (8 * k)) & 0xFF:02X}" for k in range(8))
    o(f"        .byte {b}   ; round {r:2d}\n")

# Rotation decomposition, indexed by source lane.
#
#   ROTL64(v, 8s+b) with b <= 4  ==  byte-rotate s, then rotate LEFT b
#   ROTL64(v, 8s+b) with b >  4  ==  byte-rotate s+1, then rotate RIGHT 8-b
#
# because 8s+b == 8(s+1) - (8-b). Taking whichever direction is shorter caps
# the bit passes at 4 instead of 7 and cuts the per-round total from 88 to 52.
# Verified for all 25 lanes in tools/test_keccak_ref.py.
rot_byte, rot_cnt, rot_dir = [], [], []
for i in range(25):
    s, b = K.RHO[i] >> 3, K.RHO[i] & 7
    if b <= 4:
        rot_byte.append(s); rot_cnt.append(b); rot_dir.append(0)
    else:
        rot_byte.append((s + 1) & 7); rot_cnt.append(8 - b); rot_dir.append(1)

o("\n; Fused rho+pi, indexed by SOURCE lane i = x + 5y.\n")
o("; keccak_pi_dst:  destination BYTE offset (8 * destination lane index)\n")
o("; keccak_rot_byte: whole-byte rotation — free, it is just a byte permute\n")
o(";                  applied while copying the lane into its destination\n")
o("; keccak_rot_cnt:  residual bit passes, 0..4\n")
o("; keccak_rot_dir:  0 = rotate left, 1 = rotate right (the short way round)\n")
for name, vals in (("keccak_pi_dst",   [8 * dst[i] for i in range(25)]),
                   ("keccak_rot_byte", rot_byte),
                   ("keccak_rot_cnt",  rot_cnt),
                   ("keccak_rot_dir",  rot_dir)):
    o(f"{name}:\n")
    for row in range(5):
        o("        .byte " + ", ".join(f"{vals[i]:3d}" for i in range(row * 5, row * 5 + 5)) + "\n")
